spring.application.name=authentication-server
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_server_practice
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=create-drop